DPU_DIR := dpu
HOST_DIR := host
BUILDDIR ?= build
NR_TASKLETS ?= 12
NR_DPUS ?= 2559
STACK_SIZE ?= 2048
CC = g++

define conf_filename
	${BUILDDIR}/.NR_DPUS_$(1)_NR_TASKLETS_$(2).conf
endef
CONF := $(call conf_filename,${NR_DPUS},${NR_TASKLETS})

HOST_TARGET := ${BUILDDIR}/pim_tree_host
HOST_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_host_no_shadow_subtree

DPU_INSERT_TARGET := ${BUILDDIR}/pim_tree_dpu_insert
DPU_DELETE_TARGET := ${BUILDDIR}/pim_tree_dpu_delete
DPU_SCAN_TARGET := ${BUILDDIR}/pim_tree_dpu_scan
DPU_PREDECESSOR_TARGET := ${BUILDDIR}/pim_tree_dpu_predecessor
DPU_GET_UPDATE_TARGET := ${BUILDDIR}/pim_tree_dpu_get_update
DPU_QUERY_TARGET := ${BUILDDIR}/pim_tree_dpu_query
DPU_BUILD_TARGET := ${BUILDDIR}/pim_tree_dpu_build
DPU_INIT_TARGET := ${BUILDDIR}/pim_tree_dpu_init

HOST_ENERGY_TARGET := ${HOST_TARGET}_energy
DPU_INSERT_ENERGY_TARGET := ${DPU_INSERT_TARGET}_energy
DPU_DELETE_ENERGY_TARGET := ${DPU_DELETE_TARGET}_energy
DPU_SCAN_ENERGY_TARGET := ${DPU_SCAN_TARGET}_energy
DPU_PREDECESSOR_ENERGY_TARGET := ${DPU_PREDECESSOR_TARGET}_energy
DPU_GET_UPDATE_ENERGY_TARGET := ${DPU_GET_UPDATE_TARGET}_energy
DPU_QUERY_ENERGY_TARGET := ${DPU_QUERY_TARGET}_energy
DPU_BUILD_ENERGY_TARGET := ${DPU_BUILD_TARGET}_energy
DPU_INIT_ENERGY_TARGET := ${DPU_INIT_TARGET}_energy

DPU_INSERT_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_insert_no_shadow_subtree
DPU_DELETE_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_delete_no_shadow_subtree
DPU_SCAN_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_scan_no_shadow_subtree
DPU_PREDECESSOR_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_predecessor_no_shadow_subtree
DPU_GET_UPDATE_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_get_update_no_shadow_subtree
DPU_QUERY_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_query_no_shadow_subtree
DPU_BUILD_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_build_no_shadow_subtree
DPU_INIT_TARGET_NO_SHADOW_SUBTREE := ${BUILDDIR}/pim_tree_dpu_init_no_shadow_subtree

DPU_INSERT_TARGET := ${BUILDDIR}/pim_tree_dpu_insert
DPU_DELETE_TARGET := ${BUILDDIR}/pim_tree_dpu_delete
DPU_SCAN_TARGET := ${BUILDDIR}/pim_tree_dpu_scan
DPU_PREDECESSOR_TARGET := ${BUILDDIR}/pim_tree_dpu_predecessor
DPU_GET_UPDATE_TARGET := ${BUILDDIR}/pim_tree_dpu_get_update
DPU_QUERY_TARGET := ${BUILDDIR}/pim_tree_dpu_query
DPU_BUILD_TARGET := ${BUILDDIR}/pim_tree_dpu_build
DPU_INIT_TARGET := ${BUILDDIR}/pim_tree_dpu_init

COMMON_INCLUDES := common
COMMON_INCLUDE_SOURCES := $(wildcard ${COMMON_INCLUDES}/*.h)
HOST_INCLUDES := $(wildcard ${HOST_DIR}/*.hpp) 
HOST_SOURCES := $(wildcard ${HOST_DIR}/*.cpp) 
DPU_INCLUDES := $(wildcard ${DPU_DIR}/*.h)
DPU_SOURCES := $(wildcard ${DPU_DIR}/*.c)

.PHONY: all clean test

__dirs := $(shell mkdir -p ${BUILDDIR})

OLD_COMMON_FLAGS := -Wall -Wextra -Werror -g -I${COMMON_INCLUDES}
COMMON_FLAGS := -Wall -Wextra -g -I${COMMON_INCLUDES} -Ipim_base/include/common
HOST_LIB_FLAGS := -isystem pim_base/argparse/include -isystem pim_base/parlaylib/include  -Ipim_base/include/host -Ipim_base/timer_tree/include -lpapi -lstdc++fs
HOST_FLAGS := ${COMMON_FLAGS} -std=c++17 -lpthread -O3 -I${HOST_DIR} ${HOST_LIB_FLAGS} `dpu-pkg-config --cflags --libs dpu` -DNR_TASKLETS=${NR_TASKLETS} -DNR_DPUS=${NR_DPUS}
DPU_LIB_FLAGS := -Ipim_base/include/dpu
DPU_FLAGS := ${COMMON_FLAGS} -I${DPU_DIR} ${DPU_LIB_FLAGS} -DSTACK_SIZE_DEFAULT=${STACK_SIZE} -DNR_TASKLETS=${NR_TASKLETS} -Oz

DPU_INSERT_FLAGS := ${DPU_FLAGS} -DDPU_INSERT=1 -I${DPU_DIR}
DPU_DELETE_FLAGS := ${DPU_FLAGS} -DDPU_DELETE=1 -I${DPU_DIR}
DPU_SCAN_FLAGS := ${DPU_FLAGS} -DDPU_SCAN=1 -I${DPU_DIR}
DPU_PREDECESSOR_FLAGS := ${DPU_FLAGS} -DDPU_PREDECESSOR=1 -I${DPU_DIR}
DPU_GET_UPDATE_FLAGS := ${DPU_FLAGS} -DDPU_GET_UPDATE=1 -I${DPU_DIR}
DPU_QUERY_FLAGS := ${DPU_FLAGS} -DDPU_SCAN=1 -DDPU_GET_UPDATE=1 -DDPU_PREDECESSOR=1 -I${DPU_DIR}
DPU_BUILD_FLAGS := ${DPU_FLAGS} -DDPU_BUILD=1 -I${DPU_DIR}
DPU_INIT_FLAGS := ${DPU_FLAGS} -DDPU_INIT=1 -I${DPU_DIR}

all: ${HOST_TARGET} ${HOST_TARGET_NO_SHADOW_SUBTREE} ${DPU_INSERT_TARGET} ${DPU_INSERT_TARGET_NO_SHADOW_SUBTREE} ${DPU_DELETE_TARGET} ${DPU_DELETE_TARGET_NO_SHADOW_SUBTREE} ${DPU_SCAN_TARGET} ${DPU_SCAN_TARGET_NO_SHADOW_SUBTREE} ${DPU_PREDECESSOR_TARGET} ${DPU_PREDECESSOR_TARGET_NO_SHADOW_SUBTREE} ${DPU_GET_UPDATE_TARGET} ${DPU_GET_UPDATE_TARGET_NO_SHADOW_SUBTREE} ${DPU_BUILD_TARGET} ${DPU_BUILD_TARGET_NO_SHADOW_SUBTREE} ${DPU_INIT_TARGET} ${DPU_INIT_TARGET_NO_SHADOW_SUBTREE} ${DPU_QUERY_TARGET} ${DPU_QUERY_TARGET_NO_SHADOW_SUBTREE}

${CONF}:
	$(RM) $(call conf_filename,*,*)
	touch ${CONF}

${HOST_TARGET}: ${HOST_SOURCES} ${HOST_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	$(CC) -o $@ ${HOST_SOURCES} ${HOST_FLAGS} -DSHADOW_SUBTREE=1

${HOST_TARGET_NO_SHADOW_SUBTREE}: ${HOST_SOURCES} ${HOST_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	$(CC) -o $@ ${HOST_SOURCES} ${HOST_FLAGS}

${DPU_INSERT_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_INSERT_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_INSERT_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_INSERT_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_DELETE_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_DELETE_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_DELETE_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_DELETE_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_SCAN_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_SCAN_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_SCAN_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_SCAN_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_PREDECESSOR_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_PREDECESSOR_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_PREDECESSOR_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_PREDECESSOR_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_GET_UPDATE_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_GET_UPDATE_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_GET_UPDATE_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_GET_UPDATE_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_QUERY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_QUERY_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1
	
${DPU_QUERY_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_QUERY_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_BUILD_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_BUILD_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_BUILD_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_BUILD_FLAGS} -o $@ ${DPU_SOURCES}

${DPU_INIT_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_INIT_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1

${DPU_INIT_TARGET_NO_SHADOW_SUBTREE}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_INIT_FLAGS} -o $@ ${DPU_SOURCES}


${HOST_ENERGY_TARGET}: ${HOST_SOURCES} ${HOST_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	$(CC) -o $@ ${HOST_SOURCES} ${HOST_FLAGS} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_INSERT_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_INSERT_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_DELETE_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_DELETE_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_SCAN_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_SCAN_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_PREDECESSOR_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_PREDECESSOR_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_GET_UPDATE_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_GET_UPDATE_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_QUERY_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_QUERY_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_BUILD_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	# dpu-upmem-dpurte-clang ${DPU_BUILD_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1

${DPU_INIT_ENERGY_TARGET}: ${DPU_SOURCES} ${DPU_INCLUDES} ${COMMON_INCLUDES} ${COMMON_INCLUDE_SOURCES} ${CONF}
	dpu-upmem-dpurte-clang ${DPU_INIT_FLAGS} -o $@ ${DPU_SOURCES} -DSHADOW_SUBTREE=1 -DDPU_ENERGY=1


clean:
	$(RM) -r $(BUILDDIR)

test_c: ${HOST_TARGET} ${DPU_INSERT_TARGET} ${DPU_DELETE_TARGET} ${DPU_SCAN_TARGET} ${DPU_PREDECESSOR_TARGET} ${DPU_GET_UPDATE_TARGET} ${DPU_BUILD_TARGET} ${DPU_INIT_TARGET} ${DPU_QUERY_TARGET}
	./${HOST_TARGET}

test: test_c

energy: ${HOST_ENERGY_TARGET} ${DPU_INSERT_ENERGY_TARGET} ${DPU_DELETE_ENERGY_TARGET} ${DPU_SCAN_ENERGY_TARGET} ${DPU_PREDECESSOR_ENERGY_TARGET} ${DPU_GET_UPDATE_ENERGY_TARGET} ${DPU_QUERY_ENERGY_TARGET} ${DPU_BUILD_ENERGY_TARGET} ${DPU_INIT_ENERGY_TARGET}

debug: ${HOST_TARGET} ${DPU_INSERT_TARGET} ${DPU_DELETE_TARGET} ${DPU_SCAN_TARGET} ${DPU_PREDECESSOR_TARGET} ${DPU_GET_UPDATE_TARGET} ${DPU_BUILD_TARGET} ${DPU_INIT_TARGET} ${DPU_QUERY_TARGET}
	dpu-lldb ${HOST_TARGET}

test_cpu: ${HOST_TARGET}
	./${HOST_TARGET}
